/**
 * mbaobao.com Inc.
 * Copyright (c) 2012 All Rights Reserved.
 */
package com.peigen.web.depreciate.depreciate.dal.dataobject;

import java.io.Serializable;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

// auto generated imports
import java.util.Date;

/**
 * A data object class directly models database table <tt>depreciate_product_change_log</tt>.
 *
 * This file is generated by <tt>depreciate-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/depreciate_product_change_log.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>depreciate-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
public class DepreciateProductChangeLogDO implements Serializable{
	/** Comment for <code>serialVersionUID</code> */
    private static final long serialVersionUID = -4282603875229233564L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.
	 */
	private long id;

	/**
	 * This property corresponds to db column <tt>product_id</tt>.
	 */
	private String productId;

	/**
	 * This property corresponds to db column <tt>product_current_price</tt>.
	 */
	private long productCurrentPrice;

	/**
	 * This property corresponds to db column <tt>product_change_price</tt>.
	 */
	private long productChangePrice;

	/**
	 * This property corresponds to db column <tt>raw_add_time</tt>.
	 */
	private Date rawAddTime;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public long getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(long id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>productId</tt>.
     *
     * @return property value of productId
     */
	public String getProductId() {
		return productId;
	}
	
	/**
	 * Setter method for property <tt>productId</tt>.
	 * 
	 * @param productId value to be assigned to property productId
     */
	public void setProductId(String productId) {
		this.productId = productId;
	}

    /**
     * Getter method for property <tt>productCurrentPrice</tt>.
     *
     * @return property value of productCurrentPrice
     */
	public long getProductCurrentPrice() {
		return productCurrentPrice;
	}
	
	/**
	 * Setter method for property <tt>productCurrentPrice</tt>.
	 * 
	 * @param productCurrentPrice value to be assigned to property productCurrentPrice
     */
	public void setProductCurrentPrice(long productCurrentPrice) {
		this.productCurrentPrice = productCurrentPrice;
	}

    /**
     * Getter method for property <tt>productChangePrice</tt>.
     *
     * @return property value of productChangePrice
     */
	public long getProductChangePrice() {
		return productChangePrice;
	}
	
	/**
	 * Setter method for property <tt>productChangePrice</tt>.
	 * 
	 * @param productChangePrice value to be assigned to property productChangePrice
     */
	public void setProductChangePrice(long productChangePrice) {
		this.productChangePrice = productChangePrice;
	}

    /**
     * Getter method for property <tt>rawAddTime</tt>.
     *
     * @return property value of rawAddTime
     */
	public Date getRawAddTime() {
		return rawAddTime;
	}
	
	/**
	 * Setter method for property <tt>rawAddTime</tt>.
	 * 
	 * @param rawAddTime value to be assigned to property rawAddTime
     */
	public void setRawAddTime(Date rawAddTime) {
		this.rawAddTime = rawAddTime;
	}


	/**
     * @return
     *
     * @see java.lang.Object#toString()
     */
	@Override
    public String toString() {

        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
